export interface Preset {
  label: string
  skills: string[]
}

export const PRESETS: Preset[] = [
  {
    label: 'Engineering Manager',
    skills: [
      'TypeScript',
      'Node.js',
      'PHP',
      'AWS',
      'Kubernetes',
      'Docker',
      'PostgreSQL',
      'MySQL',
      'Redis',
      'Kafka',
      'RabbitMQ',
      'SOLID',
      'DDD',
      'Solution Design',
      'API Design',
      'Architecture Patterns',
      'Bookings',
      'Payments',
      'E-commerce',
    ],
  },
  {
    label: 'Backend Lead',
    skills: [
      'TypeScript',
      'Node.js',
      'JavaScript',
      'PHP',
      'NestJS',
      'Symfony',
      'PostgreSQL',
      'MySQL',
      'MongoDB',
      'Elasticsearch',
      'Redis',
      'Kafka',
      'RabbitMQ',
      'WebSockets',
      'AWS',
      'Kubernetes',
      'Docker',
      'SOLID',
      'DDD',
      'Solution Design',
      'API Design',
      'Architecture Patterns',
    ],
  },
  {
    label: 'Principal Engineer',
    skills: [
      'TypeScript',
      'Node.js',
      'JavaScript',
      'PHP',
      'NestJS',
      'Symfony',
      'Yii',
      'PostgreSQL',
      'MySQL',
      'MongoDB',
      'Elasticsearch',
      'Redis',
      'Kafka',
      'RabbitMQ',
      'WebSockets',
      'AWS',
      'GCP',
      'Kubernetes',
      'Docker',
      'Datadog',
      'Grafana',
      'Prometheus',
      'OpenTelemetry',
      'SOLID',
      'DDD',
      'Solution Design',
      'API Design',
      'Architecture Patterns',
    ],
  },
]
